/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Precifica3D API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { orvalFetch } from './transport';
export interface CurrentUser {
  uid: string;
  email?: string | null;
}

export type EntitlementViewStatus = typeof EntitlementViewStatus[keyof typeof EntitlementViewStatus];


export const EntitlementViewStatus = {
  none: 'none',
  active: 'active',
  lapsed: 'lapsed',
} as const;

export interface EntitlementView {
  status: EntitlementViewStatus;
  source?: string | null;
  expiresAt?: string | null;
}

export type ErrorBodyDetails = { [key: string]: unknown }[] | null;

/**
 * Single source of wire error codes. Mirrored to TS via Orval (A5).
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
} as const;

export interface ErrorBody {
  code: ErrorCode;
  message: string;
  details?: ErrorBodyDetails;
  correlationId?: string | null;
}

export interface ErrorEnvelope {
  error: ErrorBody;
}

export type MarketplaceCatalogMarketplace = typeof MarketplaceCatalogMarketplace[keyof typeof MarketplaceCatalogMarketplace];


export const MarketplaceCatalogMarketplace = {
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  AMAZON: 'AMAZON',
  SHOPEE: 'SHOPEE',
} as const;

export interface PriceBand {
  minPrice: number;
  maxPrice: number | null;
  commissionPct: number | null;
  fixedFee: number | null;
}

export const FreightNoneValue = {
  kind: 'NONE',
} as const;
export type FreightNone = typeof FreightNoneValue;

export interface FreightEstimate {
  kind: 'ESTIMATE';
  thresholdPrice: number;
  defaultSubsidy: number;
  inputs?: string[] | null;
}

export interface VoucherBand {
  minPrice: number;
  maxPrice: number | null;
  voucherCeiling: number;
}

export interface FreightBandVoucher {
  kind: 'BAND_VOUCHER';
  bands: VoucherBand[];
}

export type FeeEntryDeterminants = {[key: string]: string} | null;

export interface FeeEntry {
  determinants: FeeEntryDeterminants;
  commissionPct: number | null;
  fixedFee: number | null;
  minPerItem?: number | null;
  priceBands?: PriceBand[] | null;
  freight: FreightNone | FreightEstimate | FreightBandVoucher;
  source: string;
  sourceUrl: string;
  effectiveDate: string;
  lastReviewed: string;
}

export type MarketplaceCatalogDeterminantsSchema = { [key: string]: unknown } | null;

export interface MarketplaceCatalog {
  marketplace: MarketplaceCatalogMarketplace;
  determinantsSchema?: MarketplaceCatalogDeterminantsSchema;
  entries: FeeEntry[];
}

export interface FeeCatalog {
  catalogVersion: string;
  schemaVersion: string;
  generatedAt: string;
  marketplaces: MarketplaceCatalog[];
}

export interface FilamentIn {
  name: string;
  material?: string | null;
  costPerRoll: number | string;
  rollWeightKg: number | string;
  defaultWasteGrams?: number | string;
}

export interface FilamentOut {
  id: string;
  name: string;
  material?: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  costPerRoll: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  rollWeightKg: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  defaultWasteGrams: string;
  createdAt: string;
  updatedAt: string;
}

export type HealthHealthGet200 = {[key: string]: string};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponse500 = {
  data: ErrorEnvelope
  status: 500
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
export type healthHealthGetResponseError = (healthHealthGetResponse500) & {
  headers: Headers;
};

export type healthHealthGetResponse = (healthHealthGetResponseSuccess | healthHealthGetResponseError)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health
 */
export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {

  return orvalFetch<healthHealthGetResponse>(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = ErrorEnvelope


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getMeApiV1MeGetResponse200 = {
  data: CurrentUser
  status: 200
}

export type getMeApiV1MeGetResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type getMeApiV1MeGetResponseSuccess = (getMeApiV1MeGetResponse200) & {
  headers: Headers;
};
export type getMeApiV1MeGetResponseError = (getMeApiV1MeGetResponse401) & {
  headers: Headers;
};

export type getMeApiV1MeGetResponse = (getMeApiV1MeGetResponseSuccess | getMeApiV1MeGetResponseError)

export const getGetMeApiV1MeGetUrl = () => {




  return `/api/v1/me`
}

/**
 * @summary Get Me
 */
export const getMeApiV1MeGet = async ( options?: RequestInit): Promise<getMeApiV1MeGetResponse> => {

  return orvalFetch<getMeApiV1MeGetResponse>(getGetMeApiV1MeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeApiV1MeGetQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }


export const getGetMeApiV1MeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiV1MeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeApiV1MeGet>>> = ({ signal }) => getMeApiV1MeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiV1MeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeApiV1MeGet>>>
export type GetMeApiV1MeGetQueryError = ErrorEnvelope


export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1MeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1MeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1MeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1MeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeApiV1MeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getFeeCatalogApiV1FeeCatalogGetResponse200 = {
  data: FeeCatalog
  status: 200
}

export type getFeeCatalogApiV1FeeCatalogGetResponse304 = {
  data: void
  status: 304
}

export type getFeeCatalogApiV1FeeCatalogGetResponseSuccess = (getFeeCatalogApiV1FeeCatalogGetResponse200) & {
  headers: Headers;
};
export type getFeeCatalogApiV1FeeCatalogGetResponseError = (getFeeCatalogApiV1FeeCatalogGetResponse304) & {
  headers: Headers;
};

export type getFeeCatalogApiV1FeeCatalogGetResponse = (getFeeCatalogApiV1FeeCatalogGetResponseSuccess | getFeeCatalogApiV1FeeCatalogGetResponseError)

export const getGetFeeCatalogApiV1FeeCatalogGetUrl = () => {




  return `/api/v1/fee-catalog`
}

/**
 * @summary Get Fee Catalog
 */
export const getFeeCatalogApiV1FeeCatalogGet = async ( options?: RequestInit): Promise<getFeeCatalogApiV1FeeCatalogGetResponse> => {

  return orvalFetch<getFeeCatalogApiV1FeeCatalogGetResponse>(getGetFeeCatalogApiV1FeeCatalogGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFeeCatalogApiV1FeeCatalogGetQueryKey = () => {
    return [
    `/api/v1/fee-catalog`
    ] as const;
    }


export const getGetFeeCatalogApiV1FeeCatalogGetQueryOptions = <TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeeCatalogApiV1FeeCatalogGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>> = ({ signal }) => getFeeCatalogApiV1FeeCatalogGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeeCatalogApiV1FeeCatalogGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>>
export type GetFeeCatalogApiV1FeeCatalogGetQueryError = void


export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>,
          TError,
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>,
          TError,
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Fee Catalog
 */

export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeeCatalogApiV1FeeCatalogGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getEntitlementApiV1EntitlementGetResponse200 = {
  data: EntitlementView
  status: 200
}

export type getEntitlementApiV1EntitlementGetResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type getEntitlementApiV1EntitlementGetResponseSuccess = (getEntitlementApiV1EntitlementGetResponse200) & {
  headers: Headers;
};
export type getEntitlementApiV1EntitlementGetResponseError = (getEntitlementApiV1EntitlementGetResponse401) & {
  headers: Headers;
};

export type getEntitlementApiV1EntitlementGetResponse = (getEntitlementApiV1EntitlementGetResponseSuccess | getEntitlementApiV1EntitlementGetResponseError)

export const getGetEntitlementApiV1EntitlementGetUrl = () => {




  return `/api/v1/entitlement`
}

/**
 * @summary Get Entitlement
 */
export const getEntitlementApiV1EntitlementGet = async ( options?: RequestInit): Promise<getEntitlementApiV1EntitlementGetResponse> => {

  return orvalFetch<getEntitlementApiV1EntitlementGetResponse>(getGetEntitlementApiV1EntitlementGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetEntitlementApiV1EntitlementGetQueryKey = () => {
    return [
    `/api/v1/entitlement`
    ] as const;
    }


export const getGetEntitlementApiV1EntitlementGetQueryOptions = <TData = Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEntitlementApiV1EntitlementGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>> = ({ signal }) => getEntitlementApiV1EntitlementGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEntitlementApiV1EntitlementGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>>
export type GetEntitlementApiV1EntitlementGetQueryError = ErrorEnvelope


export function useGetEntitlementApiV1EntitlementGet<TData = Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>,
          TError,
          Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntitlementApiV1EntitlementGet<TData = Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>,
          TError,
          Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEntitlementApiV1EntitlementGet<TData = Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Entitlement
 */

export function useGetEntitlementApiV1EntitlementGet<TData = Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEntitlementApiV1EntitlementGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEntitlementApiV1EntitlementGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type listFilamentsApiV1FilamentsGetResponse200 = {
  data: FilamentOut[]
  status: 200
}

export type listFilamentsApiV1FilamentsGetResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type listFilamentsApiV1FilamentsGetResponse403 = {
  data: ErrorEnvelope
  status: 403
}

export type listFilamentsApiV1FilamentsGetResponseSuccess = (listFilamentsApiV1FilamentsGetResponse200) & {
  headers: Headers;
};
export type listFilamentsApiV1FilamentsGetResponseError = (listFilamentsApiV1FilamentsGetResponse401 | listFilamentsApiV1FilamentsGetResponse403) & {
  headers: Headers;
};

export type listFilamentsApiV1FilamentsGetResponse = (listFilamentsApiV1FilamentsGetResponseSuccess | listFilamentsApiV1FilamentsGetResponseError)

export const getListFilamentsApiV1FilamentsGetUrl = () => {




  return `/api/v1/filaments`
}

/**
 * @summary List Filaments
 */
export const listFilamentsApiV1FilamentsGet = async ( options?: RequestInit): Promise<listFilamentsApiV1FilamentsGetResponse> => {

  return orvalFetch<listFilamentsApiV1FilamentsGetResponse>(getListFilamentsApiV1FilamentsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFilamentsApiV1FilamentsGetQueryKey = () => {
    return [
    `/api/v1/filaments`
    ] as const;
    }


export const getListFilamentsApiV1FilamentsGetQueryOptions = <TData = Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFilamentsApiV1FilamentsGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>> = ({ signal }) => listFilamentsApiV1FilamentsGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListFilamentsApiV1FilamentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>>
export type ListFilamentsApiV1FilamentsGetQueryError = ErrorEnvelope


export function useListFilamentsApiV1FilamentsGet<TData = Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>,
          TError,
          Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilamentsApiV1FilamentsGet<TData = Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>,
          TError,
          Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListFilamentsApiV1FilamentsGet<TData = Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Filaments
 */

export function useListFilamentsApiV1FilamentsGet<TData = Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFilamentsApiV1FilamentsGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFilamentsApiV1FilamentsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type createFilamentApiV1FilamentsPostResponse201 = {
  data: FilamentOut
  status: 201
}

export type createFilamentApiV1FilamentsPostResponse400 = {
  data: ErrorEnvelope
  status: 400
}

export type createFilamentApiV1FilamentsPostResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type createFilamentApiV1FilamentsPostResponse403 = {
  data: ErrorEnvelope
  status: 403
}

export type createFilamentApiV1FilamentsPostResponse422 = {
  data: ErrorEnvelope
  status: 422
}

export type createFilamentApiV1FilamentsPostResponseSuccess = (createFilamentApiV1FilamentsPostResponse201) & {
  headers: Headers;
};
export type createFilamentApiV1FilamentsPostResponseError = (createFilamentApiV1FilamentsPostResponse400 | createFilamentApiV1FilamentsPostResponse401 | createFilamentApiV1FilamentsPostResponse403 | createFilamentApiV1FilamentsPostResponse422) & {
  headers: Headers;
};

export type createFilamentApiV1FilamentsPostResponse = (createFilamentApiV1FilamentsPostResponseSuccess | createFilamentApiV1FilamentsPostResponseError)

export const getCreateFilamentApiV1FilamentsPostUrl = () => {




  return `/api/v1/filaments`
}

/**
 * @summary Create Filament
 */
export const createFilamentApiV1FilamentsPost = async (filamentIn: FilamentIn, options?: RequestInit): Promise<createFilamentApiV1FilamentsPostResponse> => {

  return orvalFetch<createFilamentApiV1FilamentsPostResponse>(getCreateFilamentApiV1FilamentsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(filamentIn)
  }
);}





export const getCreateFilamentApiV1FilamentsPostMutationOptions = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>, TError,{data: FilamentIn}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>, TError,{data: FilamentIn}, TContext> => {

const mutationKey = ['createFilamentApiV1FilamentsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>, {data: FilamentIn}> = (props) => {
          const {data} = props ?? {};

          return  createFilamentApiV1FilamentsPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFilamentApiV1FilamentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>>
    export type CreateFilamentApiV1FilamentsPostMutationBody = FilamentIn
    export type CreateFilamentApiV1FilamentsPostMutationError = ErrorEnvelope

    /**
 * @summary Create Filament
 */
export const useCreateFilamentApiV1FilamentsPost = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>, TError,{data: FilamentIn}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createFilamentApiV1FilamentsPost>>,
        TError,
        {data: FilamentIn},
        TContext
      > => {
      return useMutation(getCreateFilamentApiV1FilamentsPostMutationOptions(options), queryClient);
    }

export type getFilamentApiV1FilamentsFilamentIdGetResponse200 = {
  data: FilamentOut
  status: 200
}

export type getFilamentApiV1FilamentsFilamentIdGetResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type getFilamentApiV1FilamentsFilamentIdGetResponse403 = {
  data: ErrorEnvelope
  status: 403
}

export type getFilamentApiV1FilamentsFilamentIdGetResponse404 = {
  data: ErrorEnvelope
  status: 404
}

export type getFilamentApiV1FilamentsFilamentIdGetResponseSuccess = (getFilamentApiV1FilamentsFilamentIdGetResponse200) & {
  headers: Headers;
};
export type getFilamentApiV1FilamentsFilamentIdGetResponseError = (getFilamentApiV1FilamentsFilamentIdGetResponse401 | getFilamentApiV1FilamentsFilamentIdGetResponse403 | getFilamentApiV1FilamentsFilamentIdGetResponse404) & {
  headers: Headers;
};

export type getFilamentApiV1FilamentsFilamentIdGetResponse = (getFilamentApiV1FilamentsFilamentIdGetResponseSuccess | getFilamentApiV1FilamentsFilamentIdGetResponseError)

export const getGetFilamentApiV1FilamentsFilamentIdGetUrl = (filamentId: string,) => {




  return `/api/v1/filaments/${filamentId}`
}

/**
 * @summary Get Filament
 */
export const getFilamentApiV1FilamentsFilamentIdGet = async (filamentId: string, options?: RequestInit): Promise<getFilamentApiV1FilamentsFilamentIdGetResponse> => {

  return orvalFetch<getFilamentApiV1FilamentsFilamentIdGetResponse>(getGetFilamentApiV1FilamentsFilamentIdGetUrl(filamentId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFilamentApiV1FilamentsFilamentIdGetQueryKey = (filamentId: string,) => {
    return [
    `/api/v1/filaments/${filamentId}`
    ] as const;
    }


export const getGetFilamentApiV1FilamentsFilamentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError = ErrorEnvelope>(filamentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFilamentApiV1FilamentsFilamentIdGetQueryKey(filamentId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>> = ({ signal }) => getFilamentApiV1FilamentsFilamentIdGet(filamentId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: filamentId !== null && filamentId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFilamentApiV1FilamentsFilamentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>>
export type GetFilamentApiV1FilamentsFilamentIdGetQueryError = ErrorEnvelope


export function useGetFilamentApiV1FilamentsFilamentIdGet<TData = Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError = ErrorEnvelope>(
 filamentId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilamentApiV1FilamentsFilamentIdGet<TData = Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError = ErrorEnvelope>(
 filamentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFilamentApiV1FilamentsFilamentIdGet<TData = Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError = ErrorEnvelope>(
 filamentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Filament
 */

export function useGetFilamentApiV1FilamentsFilamentIdGet<TData = Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError = ErrorEnvelope>(
 filamentId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFilamentApiV1FilamentsFilamentIdGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFilamentApiV1FilamentsFilamentIdGetQueryOptions(filamentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type updateFilamentApiV1FilamentsFilamentIdPutResponse200 = {
  data: FilamentOut
  status: 200
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponse400 = {
  data: ErrorEnvelope
  status: 400
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponse403 = {
  data: ErrorEnvelope
  status: 403
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponse404 = {
  data: ErrorEnvelope
  status: 404
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponse422 = {
  data: ErrorEnvelope
  status: 422
}

export type updateFilamentApiV1FilamentsFilamentIdPutResponseSuccess = (updateFilamentApiV1FilamentsFilamentIdPutResponse200) & {
  headers: Headers;
};
export type updateFilamentApiV1FilamentsFilamentIdPutResponseError = (updateFilamentApiV1FilamentsFilamentIdPutResponse400 | updateFilamentApiV1FilamentsFilamentIdPutResponse401 | updateFilamentApiV1FilamentsFilamentIdPutResponse403 | updateFilamentApiV1FilamentsFilamentIdPutResponse404 | updateFilamentApiV1FilamentsFilamentIdPutResponse422) & {
  headers: Headers;
};

export type updateFilamentApiV1FilamentsFilamentIdPutResponse = (updateFilamentApiV1FilamentsFilamentIdPutResponseSuccess | updateFilamentApiV1FilamentsFilamentIdPutResponseError)

export const getUpdateFilamentApiV1FilamentsFilamentIdPutUrl = (filamentId: string,) => {




  return `/api/v1/filaments/${filamentId}`
}

/**
 * @summary Update Filament
 */
export const updateFilamentApiV1FilamentsFilamentIdPut = async (filamentId: string,
    filamentIn: FilamentIn, options?: RequestInit): Promise<updateFilamentApiV1FilamentsFilamentIdPutResponse> => {

  return orvalFetch<updateFilamentApiV1FilamentsFilamentIdPutResponse>(getUpdateFilamentApiV1FilamentsFilamentIdPutUrl(filamentId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(filamentIn)
  }
);}





export const getUpdateFilamentApiV1FilamentsFilamentIdPutMutationOptions = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>, TError,{filamentId: string;data: FilamentIn}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>, TError,{filamentId: string;data: FilamentIn}, TContext> => {

const mutationKey = ['updateFilamentApiV1FilamentsFilamentIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>, {filamentId: string;data: FilamentIn}> = (props) => {
          const {filamentId,data} = props ?? {};

          return  updateFilamentApiV1FilamentsFilamentIdPut(filamentId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateFilamentApiV1FilamentsFilamentIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>>
    export type UpdateFilamentApiV1FilamentsFilamentIdPutMutationBody = FilamentIn
    export type UpdateFilamentApiV1FilamentsFilamentIdPutMutationError = ErrorEnvelope

    /**
 * @summary Update Filament
 */
export const useUpdateFilamentApiV1FilamentsFilamentIdPut = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>, TError,{filamentId: string;data: FilamentIn}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFilamentApiV1FilamentsFilamentIdPut>>,
        TError,
        {filamentId: string;data: FilamentIn},
        TContext
      > => {
      return useMutation(getUpdateFilamentApiV1FilamentsFilamentIdPutMutationOptions(options), queryClient);
    }

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponse403 = {
  data: ErrorEnvelope
  status: 403
}

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponse404 = {
  data: ErrorEnvelope
  status: 404
}

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponseSuccess = (deleteFilamentApiV1FilamentsFilamentIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponseError = (deleteFilamentApiV1FilamentsFilamentIdDeleteResponse401 | deleteFilamentApiV1FilamentsFilamentIdDeleteResponse403 | deleteFilamentApiV1FilamentsFilamentIdDeleteResponse404) & {
  headers: Headers;
};

export type deleteFilamentApiV1FilamentsFilamentIdDeleteResponse = (deleteFilamentApiV1FilamentsFilamentIdDeleteResponseSuccess | deleteFilamentApiV1FilamentsFilamentIdDeleteResponseError)

export const getDeleteFilamentApiV1FilamentsFilamentIdDeleteUrl = (filamentId: string,) => {




  return `/api/v1/filaments/${filamentId}`
}

/**
 * @summary Delete Filament
 */
export const deleteFilamentApiV1FilamentsFilamentIdDelete = async (filamentId: string, options?: RequestInit): Promise<deleteFilamentApiV1FilamentsFilamentIdDeleteResponse> => {

  return orvalFetch<deleteFilamentApiV1FilamentsFilamentIdDeleteResponse>(getDeleteFilamentApiV1FilamentsFilamentIdDeleteUrl(filamentId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteFilamentApiV1FilamentsFilamentIdDeleteMutationOptions = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>, TError,{filamentId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>, TError,{filamentId: string}, TContext> => {

const mutationKey = ['deleteFilamentApiV1FilamentsFilamentIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>, {filamentId: string}> = (props) => {
          const {filamentId} = props ?? {};

          return  deleteFilamentApiV1FilamentsFilamentIdDelete(filamentId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteFilamentApiV1FilamentsFilamentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>>

    export type DeleteFilamentApiV1FilamentsFilamentIdDeleteMutationError = ErrorEnvelope

    /**
 * @summary Delete Filament
 */
export const useDeleteFilamentApiV1FilamentsFilamentIdDelete = <TError = ErrorEnvelope,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>, TError,{filamentId: string}, TContext>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFilamentApiV1FilamentsFilamentIdDelete>>,
        TError,
        {filamentId: string},
        TContext
      > => {
      return useMutation(getDeleteFilamentApiV1FilamentsFilamentIdDeleteMutationOptions(options), queryClient);
    }
