/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Precifica3D API
 * OpenAPI spec version: 0.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { orvalFetch } from './transport';
export interface CurrentUser {
  uid: string;
  email?: string | null;
}

export type ErrorBodyDetails = { [key: string]: unknown }[] | null;

/**
 * Single source of wire error codes. Mirrored to TS via Orval (A5).
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
  ENTITLEMENT_REQUIRED: 'ENTITLEMENT_REQUIRED',
} as const;

export interface ErrorBody {
  code: ErrorCode;
  message: string;
  details?: ErrorBodyDetails;
  correlationId?: string | null;
}

export interface ErrorEnvelope {
  error: ErrorBody;
}

export type MarketplaceCatalogMarketplace = typeof MarketplaceCatalogMarketplace[keyof typeof MarketplaceCatalogMarketplace];


export const MarketplaceCatalogMarketplace = {
  MERCADO_LIVRE: 'MERCADO_LIVRE',
  AMAZON: 'AMAZON',
  SHOPEE: 'SHOPEE',
} as const;

export interface PriceBand {
  minPrice: number;
  maxPrice: number | null;
  commissionPct: number | null;
  fixedFee: number | null;
}

export const FreightNoneValue = {
  kind: 'NONE',
} as const;
export type FreightNone = typeof FreightNoneValue;

export interface FreightEstimate {
  kind: 'ESTIMATE';
  thresholdPrice: number;
  defaultSubsidy: number;
  inputs?: string[] | null;
}

export interface VoucherBand {
  minPrice: number;
  maxPrice: number | null;
  voucherCeiling: number;
}

export interface FreightBandVoucher {
  kind: 'BAND_VOUCHER';
  bands: VoucherBand[];
}

export type FeeEntryDeterminants = {[key: string]: string} | null;

export interface FeeEntry {
  determinants: FeeEntryDeterminants;
  commissionPct: number | null;
  fixedFee: number | null;
  minPerItem?: number | null;
  priceBands?: PriceBand[] | null;
  freight: FreightNone | FreightEstimate | FreightBandVoucher;
  source: string;
  sourceUrl: string;
  effectiveDate: string;
  lastReviewed: string;
}

export type MarketplaceCatalogDeterminantsSchema = { [key: string]: unknown } | null;

export interface MarketplaceCatalog {
  marketplace: MarketplaceCatalogMarketplace;
  determinantsSchema?: MarketplaceCatalogDeterminantsSchema;
  entries: FeeEntry[];
}

export interface FeeCatalog {
  catalogVersion: string;
  schemaVersion: string;
  generatedAt: string;
  marketplaces: MarketplaceCatalog[];
}

export type HealthHealthGet200 = {[key: string]: string};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type healthHealthGetResponse200 = {
  data: HealthHealthGet200
  status: 200
}

export type healthHealthGetResponse500 = {
  data: ErrorEnvelope
  status: 500
}

export type healthHealthGetResponseSuccess = (healthHealthGetResponse200) & {
  headers: Headers;
};
export type healthHealthGetResponseError = (healthHealthGetResponse500) & {
  headers: Headers;
};

export type healthHealthGetResponse = (healthHealthGetResponseSuccess | healthHealthGetResponseError)

export const getHealthHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health
 */
export const healthHealthGet = async ( options?: RequestInit): Promise<healthHealthGetResponse> => {

  return orvalFetch<healthHealthGetResponse>(getHealthHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = ErrorEnvelope


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getMeApiV1MeGetResponse200 = {
  data: CurrentUser
  status: 200
}

export type getMeApiV1MeGetResponse401 = {
  data: ErrorEnvelope
  status: 401
}

export type getMeApiV1MeGetResponseSuccess = (getMeApiV1MeGetResponse200) & {
  headers: Headers;
};
export type getMeApiV1MeGetResponseError = (getMeApiV1MeGetResponse401) & {
  headers: Headers;
};

export type getMeApiV1MeGetResponse = (getMeApiV1MeGetResponseSuccess | getMeApiV1MeGetResponseError)

export const getGetMeApiV1MeGetUrl = () => {




  return `/api/v1/me`
}

/**
 * @summary Get Me
 */
export const getMeApiV1MeGet = async ( options?: RequestInit): Promise<getMeApiV1MeGetResponse> => {

  return orvalFetch<getMeApiV1MeGetResponse>(getGetMeApiV1MeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeApiV1MeGetQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }


export const getGetMeApiV1MeGetQueryOptions = <TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeApiV1MeGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeApiV1MeGet>>> = ({ signal }) => getMeApiV1MeGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeApiV1MeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMeApiV1MeGet>>>
export type GetMeApiV1MeGetQueryError = ErrorEnvelope


export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1MeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1MeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMeApiV1MeGet>>,
          TError,
          Awaited<ReturnType<typeof getMeApiV1MeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMeApiV1MeGet<TData = Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError = ErrorEnvelope>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMeApiV1MeGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeApiV1MeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getFeeCatalogApiV1FeeCatalogGetResponse200 = {
  data: FeeCatalog
  status: 200
}

export type getFeeCatalogApiV1FeeCatalogGetResponse304 = {
  data: void
  status: 304
}

export type getFeeCatalogApiV1FeeCatalogGetResponseSuccess = (getFeeCatalogApiV1FeeCatalogGetResponse200) & {
  headers: Headers;
};
export type getFeeCatalogApiV1FeeCatalogGetResponseError = (getFeeCatalogApiV1FeeCatalogGetResponse304) & {
  headers: Headers;
};

export type getFeeCatalogApiV1FeeCatalogGetResponse = (getFeeCatalogApiV1FeeCatalogGetResponseSuccess | getFeeCatalogApiV1FeeCatalogGetResponseError)

export const getGetFeeCatalogApiV1FeeCatalogGetUrl = () => {




  return `/api/v1/fee-catalog`
}

/**
 * @summary Get Fee Catalog
 */
export const getFeeCatalogApiV1FeeCatalogGet = async ( options?: RequestInit): Promise<getFeeCatalogApiV1FeeCatalogGetResponse> => {

  return orvalFetch<getFeeCatalogApiV1FeeCatalogGetResponse>(getGetFeeCatalogApiV1FeeCatalogGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFeeCatalogApiV1FeeCatalogGetQueryKey = () => {
    return [
    `/api/v1/fee-catalog`
    ] as const;
    }


export const getGetFeeCatalogApiV1FeeCatalogGetQueryOptions = <TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFeeCatalogApiV1FeeCatalogGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>> = ({ signal }) => getFeeCatalogApiV1FeeCatalogGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFeeCatalogApiV1FeeCatalogGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>>
export type GetFeeCatalogApiV1FeeCatalogGetQueryError = void


export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>,
          TError,
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>,
          TError,
          Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Fee Catalog
 */

export function useGetFeeCatalogApiV1FeeCatalogGet<TData = Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFeeCatalogApiV1FeeCatalogGet>>, TError, TData>>, request?: SecondParameter<typeof orvalFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFeeCatalogApiV1FeeCatalogGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
