"""e2 full schema

Revision ID: 0001
Revises:
Create Date: 2026-07-08 23:16:46.332534

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_uid", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("currency", sa.Text(), server_default="BRL", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("currency = 'BRL'", name=op.f("ck_accounts_currency_brl")),
        sa.PrimaryKeyConstraint("account_uid", name=op.f("pk_accounts")),
    )
    op.create_table(
        "entitlement_grants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_uid", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("granted_by", sa.Text(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('beta','comp')", name=op.f("ck_entitlement_grants_source_enum")
        ),
        sa.ForeignKeyConstraint(
            ["account_uid"],
            ["accounts.account_uid"],
            name=op.f("fk_entitlement_grants_account_uid_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlement_grants")),
    )
    op.create_index(
        op.f("ix_entitlement_grants_account_uid"),
        "entitlement_grants",
        ["account_uid"],
        unique=False,
    )
    op.create_table(
        "filaments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_uid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("material", sa.Text(), nullable=True),
        sa.Column("cost_per_roll", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("roll_weight_kg", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column(
            "default_waste_grams",
            sa.Numeric(precision=12, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cost_per_roll >= 0 AND cost_per_roll <> 'NaN'::numeric",
            name=op.f("ck_filaments_cost_per_roll_valid"),
        ),
        sa.CheckConstraint(
            "default_waste_grams >= 0 AND default_waste_grams <> 'NaN'::numeric",
            name=op.f("ck_filaments_default_waste_valid"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_filaments_name_not_blank")),
        sa.CheckConstraint("roll_weight_kg > 0", name=op.f("ck_filaments_roll_weight_positive")),
        sa.ForeignKeyConstraint(
            ["owner_uid"], ["accounts.account_uid"], name=op.f("fk_filaments_owner_uid_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filaments")),
    )
    op.create_index(op.f("ix_filaments_owner_uid"), "filaments", ["owner_uid"], unique=False)
    op.create_table(
        "printers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_uid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("machine_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("machine_lifetime_hours", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column("avg_power_kw", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column(
            "maintenance_reserve_per_hour",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "avg_power_kw >= 0 AND avg_power_kw <> 'NaN'::numeric",
            name=op.f("ck_printers_avg_power_valid"),
        ),
        sa.CheckConstraint(
            "machine_value >= 0 AND machine_value <> 'NaN'::numeric",
            name=op.f("ck_printers_machine_value_valid"),
        ),
        sa.CheckConstraint(
            "maintenance_reserve_per_hour >= 0 AND maintenance_reserve_per_hour <> 'NaN'::numeric",
            name=op.f("ck_printers_maintenance_valid"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_printers_name_not_blank")),
        sa.CheckConstraint(
            "machine_lifetime_hours > 0", name=op.f("ck_printers_lifetime_positive")
        ),
        sa.ForeignKeyConstraint(
            ["owner_uid"], ["accounts.account_uid"], name=op.f("fk_printers_owner_uid_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printers")),
    )
    op.create_index(op.f("ix_printers_owner_uid"), "printers", ["owner_uid"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_uid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("print_grams", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column(
            "waste_grams", sa.Numeric(precision=12, scale=3), server_default="0", nullable=False
        ),
        sa.Column("print_time_hours", sa.Numeric(precision=9, scale=3), nullable=False),
        sa.Column("tariff_per_kwh", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column(
            "failure_pct", sa.Numeric(precision=6, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "finish_time_hours",
            sa.Numeric(precision=9, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "finish_rate_per_hour",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "labor_hours", sa.Numeric(precision=9, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "labor_rate_per_hour",
            sa.Numeric(precision=18, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("markup_varejo_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("markup_atacado_pct", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("include_marketplace", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "channels", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "other_costs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("filament_id", sa.UUID(), nullable=True),
        sa.Column("filament_material", sa.Text(), nullable=True),
        sa.Column("filament_cost_per_roll", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("filament_roll_weight_kg", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("printer_id", sa.UUID(), nullable=True),
        sa.Column("printer_machine_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "printer_machine_lifetime_hours", sa.Numeric(precision=9, scale=3), nullable=True
        ),
        sa.Column("printer_avg_power_kw", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column(
            "printer_maintenance_reserve_per_hour", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "failure_pct >= 0 AND failure_pct <> 'NaN'::numeric",
            name=op.f("ck_products_failure_pct_valid"),
        ),
        sa.CheckConstraint(
            "filament_cost_per_roll IS NULL OR (filament_cost_per_roll >= 0 AND filament_cost_per_roll <> 'NaN'::numeric)",
            name=op.f("ck_products_filament_cost_valid"),
        ),
        sa.CheckConstraint(
            "finish_rate_per_hour >= 0 AND finish_rate_per_hour <> 'NaN'::numeric",
            name=op.f("ck_products_finish_rate_valid"),
        ),
        sa.CheckConstraint(
            "finish_time_hours >= 0 AND finish_time_hours <> 'NaN'::numeric",
            name=op.f("ck_products_finish_time_valid"),
        ),
        sa.CheckConstraint(
            "labor_hours >= 0 AND labor_hours <> 'NaN'::numeric",
            name=op.f("ck_products_labor_hours_valid"),
        ),
        sa.CheckConstraint(
            "labor_rate_per_hour >= 0 AND labor_rate_per_hour <> 'NaN'::numeric",
            name=op.f("ck_products_labor_rate_valid"),
        ),
        sa.CheckConstraint(
            "markup_atacado_pct >= 0 AND markup_atacado_pct <> 'NaN'::numeric",
            name=op.f("ck_products_markup_atacado_valid"),
        ),
        sa.CheckConstraint(
            "markup_varejo_pct >= 0 AND markup_varejo_pct <> 'NaN'::numeric",
            name=op.f("ck_products_markup_varejo_valid"),
        ),
        sa.CheckConstraint(
            "print_grams >= 0 AND print_grams <> 'NaN'::numeric",
            name=op.f("ck_products_print_grams_valid"),
        ),
        sa.CheckConstraint(
            "print_time_hours >= 0 AND print_time_hours <> 'NaN'::numeric",
            name=op.f("ck_products_print_time_valid"),
        ),
        sa.CheckConstraint(
            "printer_avg_power_kw IS NULL OR (printer_avg_power_kw >= 0 AND printer_avg_power_kw <> 'NaN'::numeric)",
            name=op.f("ck_products_printer_power_valid"),
        ),
        sa.CheckConstraint(
            "printer_machine_value IS NULL OR (printer_machine_value >= 0 AND printer_machine_value <> 'NaN'::numeric)",
            name=op.f("ck_products_printer_value_valid"),
        ),
        sa.CheckConstraint(
            "printer_maintenance_reserve_per_hour IS NULL OR (printer_maintenance_reserve_per_hour >= 0 AND printer_maintenance_reserve_per_hour <> 'NaN'::numeric)",
            name=op.f("ck_products_printer_maintenance_valid"),
        ),
        sa.CheckConstraint(
            "tariff_per_kwh >= 0 AND tariff_per_kwh <> 'NaN'::numeric",
            name=op.f("ck_products_tariff_valid"),
        ),
        sa.CheckConstraint(
            "waste_grams >= 0 AND waste_grams <> 'NaN'::numeric",
            name=op.f("ck_products_waste_grams_valid"),
        ),
        sa.CheckConstraint(
            # material is an OPTIONAL display label (nullable on `filaments`), NOT load-bearing —
            # a valid snapshot needs only the pricing inputs cost_per_roll + roll_weight_kg, so a
            # material-less filament degrades cleanly (homologation 2026-07-10).
            "filament_id IS NOT NULL OR (filament_cost_per_roll IS NOT NULL AND filament_roll_weight_kg IS NOT NULL)",
            name=op.f("ck_products_filament_link_or_snapshot"),
        ),
        sa.CheckConstraint(
            "filament_roll_weight_kg IS NULL OR filament_roll_weight_kg > 0",
            name=op.f("ck_products_filament_roll_weight_positive"),
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_products_name_not_blank")),
        sa.CheckConstraint(
            "printer_id IS NOT NULL OR (printer_machine_value IS NOT NULL AND printer_machine_lifetime_hours IS NOT NULL AND printer_avg_power_kw IS NOT NULL AND printer_maintenance_reserve_per_hour IS NOT NULL)",
            name=op.f("ck_products_printer_link_or_snapshot"),
        ),
        sa.CheckConstraint(
            "printer_machine_lifetime_hours IS NULL OR printer_machine_lifetime_hours > 0",
            name=op.f("ck_products_printer_lifetime_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["filament_id"],
            ["filaments.id"],
            name=op.f("fk_products_filament_id_filaments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_uid"], ["accounts.account_uid"], name=op.f("fk_products_owner_uid_accounts")
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_products_printer_id_printers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_filament_id"), "products", ["filament_id"], unique=False)
    op.create_index(op.f("ix_products_owner_uid"), "products", ["owner_uid"], unique=False)
    op.create_index(op.f("ix_products_printer_id"), "products", ["printer_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_printer_id"), table_name="products")
    op.drop_index(op.f("ix_products_owner_uid"), table_name="products")
    op.drop_index(op.f("ix_products_filament_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_printers_owner_uid"), table_name="printers")
    op.drop_table("printers")
    op.drop_index(op.f("ix_filaments_owner_uid"), table_name="filaments")
    op.drop_table("filaments")
    op.drop_index(op.f("ix_entitlement_grants_account_uid"), table_name="entitlement_grants")
    op.drop_table("entitlement_grants")
    op.drop_table("accounts")
    # ### end Alembic commands ###
