"""e3 boms + bom_lines

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-11

E3 kit persistence (ADR-0013/ADR-0017). Additive only — `0001` is SHIPPED and is never amended
(R4): this migration only CREATEs the two new tables. `products` is deliberately untouched — a
materialized manual product is just a row its existing link-or-snapshot CHECKs already admit,
so ADR-0017 needs no schema change there.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_uid", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_boms_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["owner_uid"], ["accounts.account_uid"], name=op.f("fk_boms_owner_uid_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boms")),
    )
    op.create_index(op.f("ix_boms_owner_uid"), "boms", ["owner_uid"], unique=False)
    op.create_index(
        "ix_boms_owner_uid_deleted_at", "boms", ["owner_uid", "deleted_at"], unique=False
    )
    op.create_table(
        "bom_lines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bom_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("print_grams", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("waste_grams", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("print_time_hours", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("tariff_per_kwh", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("failure_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("finish_time_hours", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("finish_rate_per_hour", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("labor_hours", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("labor_rate_per_hour", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("markup_varejo_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("markup_atacado_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("include_marketplace", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("filament_material", sa.Text(), nullable=True),
        sa.Column("filament_cost_per_roll", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("filament_roll_weight_kg", sa.Numeric(precision=9, scale=3), nullable=True),
        sa.Column("printer_machine_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "printer_machine_lifetime_hours", sa.Numeric(precision=9, scale=3), nullable=True
        ),
        sa.Column("printer_avg_power_kw", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column(
            "printer_maintenance_reserve_per_hour", sa.Numeric(precision=18, scale=6), nullable=True
        ),
        sa.Column(
            "channels", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "other_costs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "failure_pct IS NULL OR (failure_pct >= 0 AND failure_pct <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_failure_pct_valid"),
        ),
        sa.CheckConstraint(
            "filament_cost_per_roll IS NULL OR (filament_cost_per_roll >= 0 AND filament_cost_per_roll <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_filament_cost_valid"),
        ),
        sa.CheckConstraint(
            "finish_rate_per_hour IS NULL OR (finish_rate_per_hour >= 0 AND finish_rate_per_hour <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_finish_rate_valid"),
        ),
        sa.CheckConstraint(
            "finish_time_hours IS NULL OR (finish_time_hours >= 0 AND finish_time_hours <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_finish_time_valid"),
        ),
        sa.CheckConstraint(
            "labor_hours IS NULL OR (labor_hours >= 0 AND labor_hours <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_labor_hours_valid"),
        ),
        sa.CheckConstraint(
            "labor_rate_per_hour IS NULL OR (labor_rate_per_hour >= 0 AND labor_rate_per_hour <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_labor_rate_valid"),
        ),
        sa.CheckConstraint(
            "markup_atacado_pct IS NULL OR (markup_atacado_pct >= 0 AND markup_atacado_pct <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_markup_atacado_valid"),
        ),
        sa.CheckConstraint(
            "markup_varejo_pct IS NULL OR (markup_varejo_pct >= 0 AND markup_varejo_pct <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_markup_varejo_valid"),
        ),
        sa.CheckConstraint(
            "print_grams IS NULL OR (print_grams >= 0 AND print_grams <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_print_grams_valid"),
        ),
        sa.CheckConstraint(
            "print_time_hours IS NULL OR (print_time_hours >= 0 AND print_time_hours <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_print_time_valid"),
        ),
        sa.CheckConstraint(
            "printer_avg_power_kw IS NULL OR (printer_avg_power_kw >= 0 AND printer_avg_power_kw <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_printer_power_valid"),
        ),
        sa.CheckConstraint(
            "printer_machine_value IS NULL OR (printer_machine_value >= 0 AND printer_machine_value <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_printer_value_valid"),
        ),
        sa.CheckConstraint(
            "printer_maintenance_reserve_per_hour IS NULL OR (printer_maintenance_reserve_per_hour >= 0 AND printer_maintenance_reserve_per_hour <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_printer_maintenance_valid"),
        ),
        sa.CheckConstraint(
            "tariff_per_kwh IS NULL OR (tariff_per_kwh >= 0 AND tariff_per_kwh <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_tariff_valid"),
        ),
        sa.CheckConstraint(
            "waste_grams IS NULL OR (waste_grams >= 0 AND waste_grams <> 'NaN'::numeric)",
            name=op.f("ck_bom_lines_waste_grams_valid"),
        ),
        sa.CheckConstraint(
            "filament_roll_weight_kg IS NULL OR filament_roll_weight_kg > 0",
            name=op.f("ck_bom_lines_filament_roll_weight_positive"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_bom_lines_position_non_negative")),
        sa.CheckConstraint(
            "printer_machine_lifetime_hours IS NULL OR printer_machine_lifetime_hours > 0",
            name=op.f("ck_bom_lines_printer_lifetime_positive"),
        ),
        sa.CheckConstraint(
            "product_id IS NOT NULL OR (print_grams IS NOT NULL AND print_time_hours IS NOT NULL AND filament_cost_per_roll IS NOT NULL AND filament_roll_weight_kg IS NOT NULL AND printer_machine_value IS NOT NULL AND printer_machine_lifetime_hours IS NOT NULL AND markup_varejo_pct IS NOT NULL AND markup_atacado_pct IS NOT NULL)",
            name=op.f("ck_bom_lines_link_or_snapshot"),
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_bom_lines_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["bom_id"], ["boms.id"], name=op.f("fk_bom_lines_bom_id_boms"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_bom_lines_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_lines")),
    )
    op.create_index(op.f("ix_bom_lines_bom_id"), "bom_lines", ["bom_id"], unique=False)
    op.create_index(
        "ix_bom_lines_bom_id_position", "bom_lines", ["bom_id", "position"], unique=False
    )
    op.create_index(op.f("ix_bom_lines_product_id"), "bom_lines", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bom_lines_product_id"), table_name="bom_lines")
    op.drop_index("ix_bom_lines_bom_id_position", table_name="bom_lines")
    op.drop_index(op.f("ix_bom_lines_bom_id"), table_name="bom_lines")
    op.drop_table("bom_lines")
    op.drop_index("ix_boms_owner_uid_deleted_at", table_name="boms")
    op.drop_index(op.f("ix_boms_owner_uid"), table_name="boms")
    op.drop_table("boms")
    # ### end Alembic commands ###
